# Generated by Django 4.2.5 on 2023-11-20 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mcqpart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_year', models.IntegerField()),
                ('timer', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UnitUniversityForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Writtenpart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_part', to='practice.questionsets')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionWritten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('solution_type', models.CharField(choices=[('photo', 'Photo'), ('text', 'Text')], max_length=10)),
                ('photo_solution', models.ImageField(blank=True, null=True, upload_to='solutions/')),
                ('text_solution', models.TextField(blank=True, null=True)),
                ('Written_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_written', to='practice.writtenpart')),
            ],
        ),
        migrations.AddField(
            model_name='questionsets',
            name='unit_university_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='practice.unituniversityform'),
        ),
        migrations.CreateModel(
            name='QuestionMcq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
                ('correct_answer', models.IntegerField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')])),
                ('solution_type', models.CharField(choices=[('photo', 'Photo'), ('text', 'Text')], max_length=10)),
                ('photo_solution', models.ImageField(blank=True, null=True, upload_to='solutions/')),
                ('text_solution', models.TextField(blank=True, null=True)),
                ('Mcq_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_mcq', to='practice.mcqpart')),
            ],
        ),
        migrations.AddField(
            model_name='mcqpart',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mcq_part', to='practice.questionsets'),
        ),
    ]
