# Generated by Django 4.2.5 on 2023-11-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writtenpart',
            old_name='title',
            new_name='subject',
        ),
    ]
