# Generated by Django 4.2.5 on 2023-10-21 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quetions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectchapterform',
            name='topics',
            field=models.CharField(choices=[('None', 'None'), ('Yes', 'Yes')], default='None', max_length=4),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quetions.questionset'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionsets', to='quetions.subjectchapterform'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subject_chapter_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quetions.subjectchapterform')),
            ],
        ),
    ]
